site_name: Monggregate Documentation
site_url: https://vianneymi.github.io/monggregate/
nav:
  - Home: index.md
  - Intro: 
    - MongoDB Umbrella: intro/mongodb-umbrella.md
    - MongoDB Aggregation Framework: intro/mongodb-aggregation-framework.md
    - Why use Monggregate ?: intro/why-use-monggregate.md
  - Tutorial:
    - Getting Started: tutorial/getting-started.md
    - Pipelines: tutorial/pipeline.md
    - Stages: tutorial/stages.md
    - Operators: tutorial/operators.md
    - Search: tutorial/search.md
    - Vector Search: tutorial/vector-search.md
  - How-To:
    - Get Data: how-to/setup.md
    - Select a nested document: how-to/select-a-nested-document.md
    - Create or Update a collection: how-to/create-or-update-a-collection.md
    - Combine collections: how-to/combine-collections.md
  # - Reference:
  #   - Dollar and DollarDollar: reference/dollar.md
  - Contributing: contributing.md
  #- API Reference: api.md
  - Changelog: changelog.md

# # Using mkdocstrings to generate documentation from docstrings (API Reference)
# plugins:
#   - mkdocstrings


# Using the Material theme for styling
theme: 
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  palette:
    primary: indigo
    accent: indigo
  features:
    - content.code.annotate
    - content.code.copy

# Syntax highlighting and other extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
      use_pygments: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

# Add custom CSS for syntax highlighting
extra_css:
  - stylesheets/extra.css


