"""Tests for `monggregate.stages` subpackage."""

from monggregate.stages.bucket_auto import BucketAuto
from monggregate.stages.bucket import Bucket
from monggregate.stages.count import Count
from monggregate.stages.group import Group
from monggregate.stages.limit import Limit
from monggregate.stages.lookup import Lookup
from monggregate.stages.match import Match
from monggregate.stages.out import Out
from monggregate.stages.project import Project
from monggregate.stages.replace_root import ReplaceRoot
from monggregate.stages.sample import Sample
from monggregate.stages.set import Set
from monggregate.stages.skip import Skip
from monggregate.stages.sort_by_count import SortByCount
from monggregate.stages.sort import Sort
from monggregate.stages.stage import Stage
from monggregate.stages.union_with import UnionWith
from monggregate.stages.unset import Unset
from monggregate.stages.unwind import Unwind
from monggregate.stages.vector_search import VectorSearch